const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES'; //home
const GET_VIDEOGAMES_BY_ORIGIN = 'GET_VIDEOGAMES_BY_ORIGIN'; //JUEGOS DE LA DB
const GET_VIDEOGAMES_BY_NAME = 'GET_VIDEOGAMES_BY_NAME'; //BUSCA POR NOMBRE DE VIDEOGAME
const GET_VIDEOGAME_BY_ID = 'GET_VIDEOGAME_BY_ID';
const GET_GENRES = 'GET_GENRES';
const ORDER_ALPHABETICALLY = 'ORDER_ALPHABETICALLY'; // ORDEN ALFABETICO
const FILTER_BY_GENRES = 'FILTER_BY_GENRES';
const ORDER_BY_RATING = 'ORDER_BY_RATING'; //MAS POPULARES
const CREATED_GAMES = 'CREATED_GAMES'; // JUEGOS DE LA DB
const CREATE_GAME = 'CREATE_GAME' // POST - FORMULARIO
const MODIFY_GAME = 'MODIFY_GAME'; //PUT - FORMULARIO 
const DELETED_GAME = 'DELETED_GAME';
const DELETE_STATES = 'DELETE_STATES';
const DELETE_DETAIL = 'DELETE_DETAIL';

module.exports = {
    GET_ALL_VIDEOGAMES,
    GET_VIDEOGAMES_BY_ORIGIN,
    GET_VIDEOGAMES_BY_NAME,
    GET_VIDEOGAME_BY_ID,
    GET_GENRES,
    ORDER_ALPHABETICALLY,
    FILTER_BY_GENRES,
    ORDER_BY_RATING,
    CREATED_GAMES,
    CREATE_GAME,
    MODIFY_GAME,
    DELETED_GAME,
    DELETE_STATES,
    DELETE_DETAIL,
};